#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

TIME_BETWEEN_CHECKS = 30

#at_exit { system("sudo reboot") }

loop do
  begin
    build = Build.next_to_run
    if build
      p "Running..."  
      run = Build.next_to_run.execute

      p "Done running, output of build follows\n\n"
      p run.output

      p "Rebooting in 120 seconds"
      sleep 120
      system("sudo reboot")
    else
      p "Waiting for a build"
      sleep TIME_BETWEEN_CHECKS
    end
  rescue
  end
end

p "Something went wrong, we'll wait an hour and then reboot"
system("sleep  3600")
system("sudo reboot")
